name: 'Terraform Validation'

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '**.tf'
      - '**.tfvars'

jobs:
  validate:
    name: 'Validate Terraform'
    runs-on: self-hosted
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.6.0'

    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    - name: Terraform Init (without backend)
      run: terraform init -backend=false

    - name: Terraform Validate
      run: terraform validate

    - name: TFLint Setup
      uses: terraform-linters/setup-tflint@v4

    - name: TFLint Run
      run: |
        tflint --init
        tflint --format compact